spring.application.name=demo2

server.port=8081

spring.profiles.active=dev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
#
#management.endpoints.web.exposure.include=beans
#
#logging.level.org.springframework.beans.factory.support=DEBUG
##logging.level.org.mybatis.spring.mapper=DEBUG
#logging.level.com.baomidou.mybatisplus=DEBUG